#!/usr/bin/env python
#-*-coding:utf-8-*-

import os
import sys
import shutil
from subprocess import call

import pkg_resources
def pkg_file(fn):
    return pkg_resources.resource_filename('pandoc_agutemplate', fn)

usage = '''md2agu - Convert Markdown files to AGU journal's format
  Usage: md2agu manuscript.md
'''

if len(sys.argv) != 2:
    print(' Error: One and only one Markdown file should be given')
    print(usage)
    sys.exit()

# check if the input Markdown file is in current folder
mdfile = sys.argv[1]
print('Converting %s to AGU format' % mdfile)

fn = os.path.basename(mdfile)
if os.path.abspath(fn) != os.path.abspath(mdfile):
    print((' Error: The Markdown file should be in '
        'the current directory %s') % os.getcwd())
    sys.exit()

fn_name, fn_ext = os.path.splitext(fn)

pdf_fn = fn_name + '.pdf'
docx_fn = fn_name + '.docx'

shutil.copy(pkg_file('data/agujournal2019.cls'), os.getcwd())
shutil.copy(pkg_file('data/trackchanges.sty'), os.getcwd())
shutil.copy(pkg_file('data/agu-docx.tex'), os.getcwd())
shutil.copy(pkg_file('data/agutemplate.tex'), os.getcwd())
shutil.copy(pkg_file('data/agu-reference.docx'), os.getcwd())

call(("pandoc %s --template=%s "
    "--pdf-engine=xelatex --o %s") % (mdfile, 'agutemplate.tex', pdf_fn),
    shell=True)

call(("pandoc %s --template=%s "
    "-o test_docx.tex") % (mdfile, 'agu-docx.tex'),
    shell=True)

call(("pandoc test_docx.tex "
    "--reference-doc=%s "
    "-o %s") % ('agu-reference.docx', docx_fn), shell=True)

call("rm test_docx.tex", shell=True)
